Repository Hows-the-Air-Today/HAT-frontend-react, pull requests merged in 2023-05, with the labels that each got.

#29 🚑️ fix(HAT-382): 대기질 주간예보 서비스 로직 수정
  src/services/pmForecastService.ts
Labels: ❄️FE, 🐞 BugFix

#30 🐛 fix(HAT-373): fe게시판이슈수정
  src/api/community.js
  src/components/UI/organisms/commonstyles/styles.jsx
  src/components/pages/Community/CommunityPage.tsx
  src/components/pages/Community/styles.js
  src/components/pages/CommunityCreatPage/index.tsx
  src/components/pages/community-detail/index.js
Labels: ✨ Feature, ❄️FE, 🐞 BugFix

#32 🐛 fix(HAT-390): accessToken 추가
  src/components/pages/community-detail/index.js
Labels: ❄️FE, 🐞 BugFix

#33 🐛 fix(HAT-391): 게시판조회 무한스크롤 로딩추가
  src/components/pages/Community/CommunityPage.tsx
  src/components/pages/Community/styles.js
  src/components/pages/CommunityCreatPage/index.tsx
Labels: ✏ HTML & CSS, ✨ Feature, ❄️FE
